-- ============================================================
-- 新人業務考題抽選器：資料庫結構（Supabase / Postgres）
--
-- 怎麼執行：
--   1. 打開 Supabase 專案 → 左側 SQL Editor → New query
--   2. 把這整個檔案內容貼上 → 按 Run
--   3. 接著再執行 set_password.sql 設定管理密碼
--
-- 可重複執行：資料表用 if not exists、函式用 create or replace、
-- 種子題目只在題庫為空時才寫入，所以重跑不會報錯、也不會重複塞題。
--
-- 安全設計：資料表全部啟用 RLS 且不開放任何權限給網頁端（anon），
-- 前端只能呼叫下面的函式（RPC），管理動作都要驗證密碼。
-- ============================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------- 資料表 ----------

-- 題庫
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  category text not null check (length(btrim(category)) > 0),
  text text not null check (length(btrim(text)) > 0),
  created_at timestamptz default now()
);

-- 本輪已抽的題目（所有裝置共用）
create table if not exists public.drawn (
  question_id bigint primary key references public.questions(id) on delete cascade,
  drawn_at timestamptz default now()
);

-- 每個分類最近一次抽出的題（新一輪第一題要避開它）
create table if not exists public.category_last (
  category text primary key,
  question_id bigint
);

-- 管理密碼雜湊（只會有一列）
create table if not exists public.app_secret (
  id int primary key check (id = 1),
  pw_hash text not null
);

-- 全部啟用 RLS，不建任何 policy，並收回所有人的直接存取權
alter table public.questions     enable row level security;
alter table public.drawn         enable row level security;
alter table public.category_last enable row level security;
alter table public.app_secret    enable row level security;

revoke all on table public.questions     from public, anon, authenticated;
revoke all on table public.drawn         from public, anon, authenticated;
revoke all on table public.category_last from public, anon, authenticated;
revoke all on table public.app_secret    from public, anon, authenticated;
revoke all on sequence public.questions_id_seq from public, anon, authenticated;

-- ---------- 內部小工具：密碼檢查（不開放給前端直接呼叫） ----------

-- 回傳密碼是否正確；尚未設密碼（app_secret 沒資料）一律視為錯誤
create or replace function public._pw_ok(p_pw text)
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1 from public.app_secret s
    where s.id = 1 and s.pw_hash = crypt(p_pw, s.pw_hash)
  );
$$;

-- 密碼錯誤就延遲 0.5 秒（拖慢暴力猜測）後丟 invalid_password
create or replace function public._assert_pw(p_pw text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public._pw_ok(p_pw) then
    perform pg_sleep(0.5);
    raise exception 'invalid_password';
  end if;
end;
$$;

revoke execute on function public._pw_ok(text)     from public, anon, authenticated;
revoke execute on function public._assert_pw(text) from public, anon, authenticated;

-- ---------- 公開函式（不需密碼） ----------

-- 各分類題數與本輪剩餘題數
create or replace function public.list_categories()
returns table(category text, total int, remaining int)
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
#variable_conflict use_column
begin
  return query
    select q.category,
           count(*)::int,
           (count(*) - count(d.question_id))::int
    from public.questions q
    left join public.drawn d on d.question_id = q.id
    group by q.category
    order by q.category;
end;
$$;

-- 依序每個分類各抽 1 題
create or replace function public.draw_questions(p_cats text[])
returns table(id bigint, category text, text text, total int, remaining int, new_round boolean)
language plpgsql
security definer
set search_path = public, extensions
as $$
#variable_conflict use_column
declare
  v_seen text[] := '{}';
  v_cat text;
  v_total int;
  v_pick bigint;
  v_text text;
  v_new boolean;
  v_left int;
begin
  if p_cats is null or coalesce(array_length(p_cats, 1), 0) = 0 then
    raise exception '請至少選一個分類';
  end if;

  -- 同時間只允許一個人抽題，避免兩人抽到同一題
  perform pg_advisory_xact_lock(hashtext('exam_draw_questions'));

  for v_cat in select c from unnest(p_cats) with ordinality as t(c, n) order by n loop
    -- 重複的分類只算一次
    if v_cat is not null and v_cat = any(v_seen) then
      continue;
    end if;
    v_seen := v_seen || coalesce(v_cat, '');

    select count(*)::int into v_total from public.questions q where q.category = v_cat;
    if v_total = 0 then
      raise exception '分類不存在：%', coalesce(v_cat, '(空白)');
    end if;

    v_new := false;

    -- 先從「本輪未抽」挑
    select q.id into v_pick
    from public.questions q
    where q.category = v_cat
      and not exists (select 1 from public.drawn d where d.question_id = q.id)
    order by random()
    limit 1;

    if v_pick is null then
      -- 本輪抽完：清掉該分類已抽記錄，開新一輪（題數>1 時避開上一題）
      delete from public.drawn d
      where d.question_id in (select q.id from public.questions q where q.category = v_cat);
      v_new := true;

      select q.id into v_pick
      from public.questions q
      where q.category = v_cat
        and (v_total = 1
             or q.id is distinct from (select l.question_id from public.category_last l where l.category = v_cat))
      order by random()
      limit 1;
    end if;

    insert into public.drawn (question_id) values (v_pick)
    on conflict (question_id) do update set drawn_at = now();

    insert into public.category_last (category, question_id) values (v_cat, v_pick)
    on conflict (category) do update set question_id = excluded.question_id;

    select q.text into v_text from public.questions q where q.id = v_pick;

    select (v_total - count(*))::int into v_left
    from public.drawn d
    join public.questions q on q.id = d.question_id
    where q.category = v_cat;

    id := v_pick;
    category := v_cat;
    text := v_text;
    total := v_total;
    remaining := v_left;
    new_round := v_new;
    return next;
  end loop;
end;
$$;

-- ---------- 管理函式（需要密碼） ----------

create or replace function public.admin_login(p_pw text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if public._pw_ok(p_pw) then
    return true;
  end if;
  perform pg_sleep(0.5);
  return false;
end;
$$;

create or replace function public.admin_list_questions(p_pw text)
returns table(id bigint, category text, text text, drawn boolean)
language plpgsql
security definer
set search_path = public, extensions
as $$
#variable_conflict use_column
begin
  perform public._assert_pw(p_pw);
  return query
    select q.id, q.category, q.text,
           exists (select 1 from public.drawn d where d.question_id = q.id)
    from public.questions q
    order by q.category, q.id;
end;
$$;

create or replace function public.admin_save_question(p_pw text, p_id bigint, p_category text, p_text text)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_cat text := btrim(coalesce(p_category, ''));
  v_txt text := btrim(coalesce(p_text, ''));
  v_old text;
  v_id bigint;
begin
  perform public._assert_pw(p_pw);

  if v_cat = '' then raise exception '分類不可空白'; end if;
  if v_txt = '' then raise exception '題目內容不可空白'; end if;

  if p_id is null then
    insert into public.questions (category, text) values (v_cat, v_txt)
    returning id into v_id;
    return v_id;
  end if;

  select q.category into v_old from public.questions q where q.id = p_id for update;
  if not found then
    raise exception '找不到題目：%', p_id;
  end if;

  update public.questions set category = v_cat, text = v_txt where id = p_id;

  -- 換分類時，把這題從已抽記錄移除，避免記錄錯亂
  if v_old is distinct from v_cat then
    delete from public.drawn where question_id = p_id;
  end if;

  return p_id;
end;
$$;

create or replace function public.admin_delete_question(p_pw text, p_id bigint)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform public._assert_pw(p_pw);
  delete from public.questions where id = p_id; -- drawn 由 cascade 一併清除
end;
$$;

create or replace function public.admin_rename_category(p_pw text, p_old text, p_new text)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_new text := btrim(coalesce(p_new, ''));
  v_count integer;
begin
  perform public._assert_pw(p_pw);

  if v_new = '' then raise exception '新分類名稱不可空白'; end if;

  update public.questions set category = v_new where category = p_old;
  get diagnostics v_count = row_count;

  -- 舊分類的「最近一題」記錄刪掉即可
  if p_old is distinct from v_new then
    delete from public.category_last where category = p_old;
  end if;

  return v_count;
end;
$$;

create or replace function public.admin_reset(p_pw text, p_category text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform public._assert_pw(p_pw);

  if p_category is null then
    delete from public.drawn where true;
    delete from public.category_last where true;
  else
    delete from public.drawn
    where question_id in (select q.id from public.questions q where q.category = p_category);
    delete from public.category_last where category = p_category;
  end if;
end;
$$;

-- ---------- 函式權限：收回所有人，只開放 anon（網頁端）呼叫 ----------

revoke execute on function public.list_categories()                                   from public, anon, authenticated;
revoke execute on function public.draw_questions(text[])                               from public, anon, authenticated;
revoke execute on function public.admin_login(text)                                    from public, anon, authenticated;
revoke execute on function public.admin_list_questions(text)                           from public, anon, authenticated;
revoke execute on function public.admin_save_question(text, bigint, text, text)        from public, anon, authenticated;
revoke execute on function public.admin_delete_question(text, bigint)                  from public, anon, authenticated;
revoke execute on function public.admin_rename_category(text, text, text)              from public, anon, authenticated;
revoke execute on function public.admin_reset(text, text)                              from public, anon, authenticated;

grant execute on function public.list_categories()                                     to anon;
grant execute on function public.draw_questions(text[])                                to anon;
grant execute on function public.admin_login(text)                                     to anon;
grant execute on function public.admin_list_questions(text)                            to anon;
grant execute on function public.admin_save_question(text, bigint, text, text)         to anon;
grant execute on function public.admin_delete_question(text, bigint)                   to anon;
grant execute on function public.admin_rename_category(text, text, text)               to anon;
grant execute on function public.admin_reset(text, text)                               to anon;

-- ---------- 種子資料：題庫為空時才寫入原本的 20 題 ----------

do $seed$
begin
  if not exists (select 1 from public.questions) then
    insert into public.questions (id, category, text) values
      (1,  $$詢價$$, $$你好～請問勁戰六代現在有現車嗎？大概多少錢啊？$$),
      (2,  $$詢價$$, $$老闆我想買二手的 JET SL，三年內的就好，預算八萬左右，有推薦的嗎$$),
      (3,  $$詢價$$, $$你們新車 Gogoro 現在有什麼優惠？我看網路上價格差很多，想先問清楚$$),
      (4,  $$詢價$$, $$我朋友說你們這邊的 Force 價格比較漂亮，可以給我報個價嗎？要含領牌那種$$),
      (5,  $$殺價$$, $$這台 DRG 你們開 12 萬太貴了吧，隔壁家才 11 萬出頭，你們能不能比照？$$),
      (6,  $$殺價$$, $$如果我今天就下訂，可以再便宜一點嗎？零頭抹掉也好啦～$$),
      (7,  $$殺價$$, $$這台二手 SYM 三寶車況看起來普通，價格好像偏高，最低多少你直接說吧$$),
      (8,  $$殺價$$, $$我是學生預算真的有限，可以送我安全帽跟置物箱嗎？不然我再考慮看看$$),
      (9,  $$客訴$$, $$我上禮拜才買的車，今天發現龍頭有異音，你們賣我之前到底有沒有檢查過？$$),
      (10, $$客訴$$, $$說好三天交車現在都第七天了，也沒人通知我，到底什麼時候可以牽車？$$),
      (11, $$客訴$$, $$車價跟當初講的不一樣欸，怎麼多了一堆雜費？你們這樣我會很困擾$$),
      (12, $$客訴$$, $$昨天去店裡修車，等了兩個多小時才輪到我，而且也沒人跟我說要等這麼久$$),
      (13, $$交車$$, $$請問我訂的車什麼時候可以來拿？需要帶什麼證件嗎？$$),
      (14, $$交車$$, $$我下禮拜出差，可以讓我家人代替我去牽車嗎？他需要帶什麼？$$),
      (15, $$交車$$, $$車牌下來了嗎？我想週末直接騎去環島，想確認一下來不來得及$$),
      (16, $$交車$$, $$交車的時候可以順便教我怎麼用儀表板嗎？我第一次買機車，什麼都不太懂$$),
      (17, $$售後$$, $$老闆，我買的車已經跑一千公里了，是不是該回去做第一次保養了？費用大概多少？$$),
      (18, $$售後$$, $$我的車最近早上發動比較困難，要騎過去給你們看嗎？還是先怎麼處理？$$),
      (19, $$售後$$, $$請問保固期間輪胎被扎到算保固範圍嗎？我剛剛才補了一下$$),
      (20, $$售後$$, $$上次裝的行車記錄器好像沒電了，是不是要回去調整？你們什麼時候有空$$);

    -- 把自動編號校正到目前最大 id 之後
    perform setval(pg_get_serial_sequence('public.questions', 'id'), (select max(id) from public.questions));
  end if;
end
$seed$;
